version: "3.3"

services:
  auth-db:
    container_name: auth-db
    image: 'mongo'
    restart: always
    volumes:
      - mongo-volume:/data/db
      #- ./mongo-volume:/data/db
    ports:
      - 27018:27017

  authentication-authorization-service:
    container_name: authn-authz-service-v0.1
    image: authn-authz-service-v0.1-image
    build: .
    #command: bash -c "java -jar /build/libs/Pigihi-AuthN-AuthZ-0.0.1-SNAPSHOT.jar"
    volumes:
      - .:/app
    ports:
      - 8099:8080
    restart: always
    depends_on:
      - auth-db

volumes:
  mongo-volume:

networks:
  default:
    external:
      name: pigihi-network
