eureka_hostname: service-registry
mongodb_hostname: auth-db

# Production environment
#mongodb_database_name: authDB

# Development environment
mongodb_database_name: devAuthDB

# Test environment
#mongodb_database_name: testAuthDB

# Eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka_hostname}:8761/eureka
  instance:
    hostname: localhost

# Server properties
server:
  port: 8099

# Application properties
spring:
  application:
    name: AUTH-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: ${mongodb_database_name}
      host: ${mongodb_hostname}
      port: 27017
  config:
    import: optional:settings.yml
