# Eureka properties
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    hostname: localhost

# Server properties
server:
  port: 8080

# Application properties
spring:
  application:
    name: AUTH-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: testWorkingDB
# The name of the mongodb docker service is set as the host
#      host: auth-db
      host: localhost
      port: 27017
  config:
    import: settings.yml
