# Test environment
#mongodb_hostname: auth-db
#mongodb_database_name: testAuthDB

# Server properties
server:
  port: 8099

# Application properties
spring:
  application:
    name: AUTH-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: ${mongodb_database_name}
      host: ${mongodb_hostname}
      port: 27017
  config:
    import: optional:settings.yml
  profiles:
    active: standalone
